Add linter for golangci.yml | fix linter errors in golangci.yml
smallstep/workflows pull request #112
Opened 2024-07-15 17:10 UTC by dopey

2024-07-15 18:32 UTC, azazeal commented on .github/workflows/ci.yml
> +  push:
Maybe on PR too?

2024-07-16 12:21 UTC, azazeal requested changes

2024-07-16 12:21 UTC, azazeal commented on .github/workflows/ci.yml
> +  push:
This needs to run on PR too, @dopey

2024-07-17 01:38 UTC, maraino approved these changes
Consider to add reopened

2024-07-17 01:38 UTC, maraino commented on .github/workflows/ci.yml
> +      - synchronize
We can add `reopened`, those 3 are the default values.

2024-07-17 02:12 UTC, maraino approved these changes

2024-07-17 02:24 UTC, merged